spring.application.name=auth
spring.cloud.config.name=auth
server.port=8087
spring.config.import=configserver:${CONFIG_URL:http://localhost:8888}
spring.main.allow-bean-definition-overriding=true
#spring.liquibase.change-log=classpath:db/changelog.xml
